### ISSUE TITLE
General NuSpec support

### ISSUE THREAD

**Issue by fwinkelbauer** [ploeh/ZeroToNine#24]
Hey,

I was wondering if you have thought about supporting *.nuspec files (NuGet and Chocolatey) in addition to any AssemblyInfo.* files when using `zero29.exe`.

In other words: a call to `zero29.exe` could also search for *.nuspec files in the current working directory and update their version tag as well.

Is this something that could be desirable for this project?

**Comment by ploeh** [comment]
Thank you for writing 👍 

I do, indeed, have some thoughts on that topic 😄 

The purpose of ZeroToNine is to manage `AssemblyInfo` files. That's it.

While it _could_ also manage `.nuspec` files, it would dilute its purpose. The next feature request, then, would be someone else's XML file, or a YAML file that someone uses in their build process, and so on.

There are other tools that can solve the problem of taking the version from a compiled assembly or an `AssemblyInfo` file, and apply that version to a templated `.nuspec` file. One such tool (that I use myself) is [FAKE](http://fsharp.github.io/FAKE); here's [an example](https://github.com/ploeh/Numsense/blob/master/Build.fsx#L21).

ZeroToNine was created with the Unix philosophy in mind: _do one thing, and do it well._ I don't think it's desirable to enable it to change `.nuspec` files as well.

**Comment by fwinkelbauer** [comment]
I have thought about doing it in [Cake](http://cakebuild.net/) as my first impulse. The second thought I had was "but I want the version of all these files to be set by one tool". On closer examination thought I could see that supporting nusepcs would also mean that one would have to ignore certain folders such as the `packages` folder and it's only downhill from there (feature bloat).

So all in all I agree with your view, it just took me some time to "get there". I'll deal with all other stuff in the build tool.

Thank you for your work!

**Comment by ploeh** [comment]
To be fair, many build tools are a bit bloated as well, so another option could be to find (or develop) a more specialised tool for that specific purpose. Doesn't `nuget.exe` contain some support for replacing placeholders with values?

**Comment by fwinkelbauer** [comment]
While that is true I find Cake more appealing than e.g. psake because it gives me some easy options to generalize build steps (e.g. at work). And performing a task such as injecting the version from an AssemblyInfo file into a pack command (either NuGet or Chocolatey) is really easy.

I haven't looked much into Fake, but learning some F# is on my list haha!

`nuget.exe` does support some nice placeholder features (e.g. the `$version$` token) if it is paired with a `.csproj` file, but `chocolatey.exe` is a little different from my current experience. But as choco/nuget packages are for the most part only created using some build scripts (instead of triggering it through Visual Studio UI) I'm fine with injecting version information through some build script magic

**Comment by fwinkelbauer** [comment]
If you are curious: [Nuget $version$ token explained](http://www.xavierdecoster.com/post/2012/04/26/nuget-version-token-explained):

> Basically, it comes down to this:
> - If the AssemblyInformationalVersion attribute is available, then that one is used.
> - If the AssemblyInformationalVersion attribute is not available, then the AssemblyVersion attribute is used.
> - If none of the above are specified, your assembly will have a version number of 0.0.0.0, as well as the resulting package.
> - NuGet totally ignores the AssemblyFileVersion attribute.

**Edit:** For anyone who might be interested, I've scratched my own back by writing [Bumpy](https://github.com/fwinkelbauer/Bumpy)
